matrix:
  fast_finish: true
  allow_failures:
  - env: JOB=APK
  - env: JOB=IPA
  include:
  - env: JOB=PR
    os: linux
    language: generic
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git
    script:
    - "./flutter/bin/flutter test"
  - env: JOB=APK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-25.0.3
      - android-25
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
    - unzip -qq gradle-3.5-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.5
    - export PATH=$GRADLE_HOME/bin:$PATH
    - git clone https://github.com/flutter/flutter.git
    script:
    - "./flutter/bin/flutter test"
  - env: JOB=IPA
    os: osx
    language: generic
    osx_image: xcode8.3
    before_script:
    - brew update
    - brew install libimobiledevice
    - brew install ideviceinstaller
    - brew install ios-deploy
    - git clone https://github.com/flutter/flutter.git
    script:
    - "./flutter/bin/flutter test"
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: vYA2YCMpCcbCDCUieJN+5tty6htVdo5Mga9YCfp+EsYD3WQUY4w1rU/geP22wjUXTg6XB21tKjdTkiJe1dXC2zFpl37QbfSIs0tWRa/O0SUxE1HPi5T5WtuL60Jzuh+69z1vnAuJ1tF4nFiiKdpVQuZe2bUaITbmEYu3nuRc2syyNMPtLYuZ/AU4hhq74XEzMvc41M3gFLO9kpIvlscwDeoyrAte1D6KOTBdUf9cUwLvQ05A4cfAfnWgWmSlK6SFKJXCxCLkiLnSpPdXP5adnT9W9LzFtUacRJlsRno6TtxhZpURzdOXayk5u1NeATTIKkYLlFJ8sszyUa2AkgkBgFajdFXqcjF2gR0JMgel9zGextaj05O4hVRAnNENeq5ZQpFn9ecaq9Nph8Cxa1NmQcXQfDWDQRsumUTDhohiSKABakcykjy5gIDfEc9Fl7jHjI+ZZkehw/9MYkMi4z4GCl3sAQzYuhXiRumGo8mxj3PA50LvS0JinM1d0OrrM8IVuQiM5L1y15Qs9ehMXOVvFIhvn+174lP4XvrGw62MEu0vROKhBQfgKy0iDxtOrYn6wLE479JiDvAiDyICfb88PVMlYEBllS2BhzkG5LKarqKfUeJ2a7TmY8DiDlS01uhdja52EVXR7ZeZ3xHyVD8MpLGOegz/wpIccFoAOyhA0gw=
