name: "khel_ke_baat_karen"
description: "App for autistic children."

version: 1.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  scoped_model: "1.0.1"
  http: "^0.12.0+2"
  rect_getter: "0.0.1"
  flutter_spinkit: "^3.1.0"
  animated_text_kit: ^1.3.0
  fancy_bottom_navigation: "^0.3.2"
  image_picker: "^0.5.4"
  mime: "^0.9.6+2"
  shared_preferences: "^0.5.2"
  rxdart: "^0.21.0"
  url_launcher: "^5.0.2"
  flutter_tts: "^0.2.4"
  sqflite: "^1.1.5"
  path_provider: "^0.5.0+1"
  dotenv: "^1.0.0"
  flutter_secure_storage: "^3.2.1+1"
  audioplayers: "any"
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/food.jpg
    - assets/background.jpg
    - assets/loader.jpg
    - assets/reward.png
    - assets/avtar.png
    - 'success.mp3'

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/Oswald-Bold.ttf
          weight: 700
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true